config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#index'

  resources :dashboards

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:index, :new, :create, :show]

  resources :search, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  
  validates :town,
    presence: true
  validates :country,
    presence: true
end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :user
end

app/models/lead_search.rb
class LeadSearch < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  
  # validates :first_name,
  #   presence: true
  # validates :last_name,
  #   presence: true
  validates :email,
    presence: true
  validates :password,
    presence: true,
    length: { in: 6..30, message: "password incorrect"}
  belongs_to :city
  has_many :leads
  has_many :lead_searchs


  def info
    return "User #{id} info is #{first_name}, #{last_name}, #{age}, #{email}, #{job}."
  end

  def full_name
    first_name + " " + last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user, only: [:index, :show, :destroy] 

  def index
    @leads = Lead.all
  end

  def show
    @lead = Lead.find(params[:id])
  end

  def destroy
    @lead = Lead.find(params[:id])
    if @lead.destroy 
      flash[:primary] = "Ton gossip a bien été supprimé."
      redirect_to dashboard_path
      return
    else
    end
  end

  private 

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/search_controller.rb
require 'nokogiri'
require 'open-uri'

class SearchController < ApplicationController
  def index

  end

  def new
    @lead = LeadSearch.new
  end

  def create 
    scrap 
    render :show
  end 

  private

  def scrap
    @h = Hash.new{|hsh, key| hsh[key] = []}

    @doc = Nokogiri::HTML(open(whole_search))
    @doc.xpath('//h3/a').each do |node|
      lead = node.text.split(/(?=-)/)
      @h[:name] << lead[0]
      @h[:job] << lead[1]
    end
    
    @doc.xpath('//h3/a/@href').each do |node|
      url = node.text[7..-1]
      final_url = url.slice(0..(url.index('&')))
      @h[:url] << final_url.chomp('&')
    end
  end


  def whole_search
    google_url = %Q(http://www.google.com/search?q=)
    @company_name = params[:search]
    @request = %Q(#{google_url}#{@company_name}"+%2B+"CEO"+OR+"Fondateur"+OR+"Fondatrice"+OR+"DG"+OR+"PDG"+%2B+Paris+site%3Alinkedin.com%2Fin)
    return @request
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      flash[:success] = "Welcome back #{user.first_name}!"
      session[:user_id] = user.id
      redirect_to dashboards_path
    else
      flash[:danger] = "Mauvaise combinaison réessaye !"
      render 'new'
    end
  end

  def destroy
    if session.delete(:user_id)
      flash[:primary] = "Tu as bien été deconnecté. A bientôt !"
      redirect_to root_path
      return
    else
    end
  end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(
      first_name: params[:first_name], 
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      city_id: 1
      )
      if @user.save
        flash[:success] = "Compte créé. Bienvenue #{@user.first_name}!"
        session[:user_id] = @user.id
        redirect_to root_path
        return
      else
        flash[:danger] = "Informations invalides, réessaye."
        render :new
      end
  end

  def show
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<div class="container pt-5 mb-4">
  <h1>La liste de tes leads</h1>
  <div class="row pt-4 pb-4">
    <table class="table">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">First_name</th>
          <th scope="col">Last_name</th>
          <th scope="col">Phone Number</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @leads.each do |lead| %>
          <tr>
            <th scope="row"><%= lead.id %></th>
            <td><%= lead.first_name %></td>
            <td><%= lead.last_name %></td>
            <td><%= lead.phone_number %></td>
            <td><a href="<%= dashboard_path(lead.id)%>"><i class="fas fa-eye"></i></a></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lidzi</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light">
      <a class="navbar-brand" href="<%= root_path %>">Lidzi</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="<%=root_path%>">Home</a>
          </li>
        </ul>
        <% if session[:user_id].nil? %>
        <span class="navbar-text">
          <a href="<%= new_user_path %>" class="nav-link text-light">Sign Up</a>
        </span>
        <span class="navbar-text">
          <a href="<%= new_session_path %>" class="nav-link text-light">Log In</a>
        </span>
        <% end %>
        <% if session[:user_id] %>
        <span class="nav-item">
          <a class="nav-link text-light" <%= link_to "Search", new_search_path %>
        </span>
        <span class="nav-item">
          <a class="nav-link text-light" <%= link_to "Log Out", session_path(session[:user_id]), method: :delete %>
        </span>
        <% end %>
      </div>
    </nav>

    <!-- FLASH ALERT -->
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %> text-center" role="alert">
        <%= msg %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<div class="container">
    <br/>
	<div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search"></i>
                    </div>
                    <!--end of col-->

                    <div class="col">
                    <%= form_tag url_for(action: 'create'), method: "post" do %>
                        <%= text_field_tag(:search, "", class: 'form-control form-control-lg form-control-borderless', placeholder: 'Search something') %>
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <%= submit_tag "Search", class: 'btn btn-lg btn-success' %>
                    </div>
                    <% end %>
                    <!--end of col-->
                </div>
            </div>
        </div>
        <!--end of col-->
    </div>
</div>

app/views/search/new.html.erb
<div class="container">
    <br/>
	<div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search"></i>
                    </div>
                    <!--end of col-->

                    <div class="col">
                    <%= form_tag url_for(action: 'create'), method: "post" do %>
                        <%= text_field_tag(:search, "", class: 'form-control form-control-lg form-control-borderless', placeholder: 'Search something') %>
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <%= submit_tag "Search", class: 'btn btn-lg btn-success' %>
                    </div>
                    <% end %>
                    <!--end of col-->
                </div>
            </div>
        </div>
        <!--end of col-->
    </div>
</div>

app/views/search/show.html.erb
<div class="container">
    <br/>
	<div class="row justify-content-center">
        <div class="col-12 col-md-10 col-lg-8">
            <div class="card card-sm">
                <div class="card-body row no-gutters align-items-center">
                    <div class="col-auto">
                        <i class="fas fa-search"></i>
                    </div>
                    <!--end of col-->

                    <div class="col">
                    <%= form_tag url_for(action: 'create'), method: "post" do %>
                        <%= text_field_tag(:search, "", class: 'form-control form-control-lg form-control-borderless', placeholder: 'Search something') %>
                    </div>
                    <!--end of col-->
                    <div class="col-auto">
                        <%= submit_tag "Search", class: 'btn btn-lg btn-success' %>
                    </div>
                    <% end %>
                    <!--end of col-->
                </div>
            </div>
        </div>
        <!--end of col-->
    </div>
</div>

<div class="container pt-5 mb-4">
  <div class="row pt-4 pb-4">
  <h3>Recherche des dirigeants de <%= @company_name %></h3>
    <table class="table">
      <thead class="table-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">First Name</th>
          <th scope="col">Job Title</th>
          <th scope="col">LinkedIn</th>
          <th scope="col">Save</th>
        </tr>
      </thead>
      <tbody>
        <% 5.times do |i| %>
        <tr>
          <th scope="row"><%= i + 1 %></th>
          <td><%= @h[:name][i] %></td>
          <td><%= @h[:job][i] %></td>
          <td><a href="<%= @h[:url][i] %>"><i class="fab fa-linkedin-in"></i></a></td>
          <td><a href=""><i class="far fa-save"></i></a></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/statics/index.html.erb
<h1> HELLO A TOUS </h1>

app/views/users/new.html.erb
<div class="container mb-5">
<h1 class="pt-3"> Créer ton compte !</h1>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
      <%= label_tag 'Prénom' %>
      <%= text_field_tag 'first_name', @user.first_name, class: 'form-control',  placeholder: "ex : Michel" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Nom de Famille' %>
      <%= text_field_tag 'last_name', @user.last_name, class: 'form-control',  placeholder: "ex : Gondri" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Age' %>
      <%= text_field_tag 'age', @user.age, class: 'form-control',  placeholder: "ex : 76 ans" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Email' %>
      <%= text_field_tag 'email', @user.email, class: 'form-control',  placeholder: "ex : michel76@gondri.com" %>
    </div>
    <div class="form-group">
      <%= label_tag 'Mot de Passe' %>
      <%= password_field_tag 'password', @user.password, class: 'form-control',  placeholder: "ex : Mich76!Gondr1928" %>
    </div>

      <%= submit_tag "Créer ton compte", class: 'btn btn-default btn-dark text-light btn-submit' %>
    <% end %>
</div>